REVOKE ALL ON FUNCTION public.edge_complete_onboarding(
  UUID, TEXT, INTEGER, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT,
  BOOLEAN, TIME, BOOLEAN, TEXT
) FROM PUBLIC, anon, authenticated;

GRANT EXECUTE ON FUNCTION public.edge_complete_onboarding(
  UUID, TEXT, INTEGER, NUMERIC, NUMERIC, NUMERIC, NUMERIC, TEXT, TEXT,
  BOOLEAN, TIME, BOOLEAN, TEXT
) TO project_admin;
